---
- name: Install docker dependancies
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install Docker Engine
    apt:
      name: docker-ce
      state: present
      update_cache: true

- name: Pull image
      community.docker.docker_image_pull:
        name: activecm/rita
        tag: 4.3.1

    - name: Start container
      community.docker.docker_container:
        detach: true
        image: activecm/rita:4.3.1

    - name: Show output
      ansible.builtin.debug:
        msg: "{{ output.container.Output }}"
