- name: Adding aliases
  loop: "{{ aliases | dict2items }}"
  lineinfile:
    path: /etc/hosts
    line: "{{ item.value }} {{ item.key }}"

- name: Add zip's password to the fasttrack wordlist
  lineinfile:
    path: /usr/share/wordlists/fasttrack.txt
    line: IhateMyJob

- name: Create /home/user/hacking directory
  file:
    path: /home/user/hacking
    state: directory
    owner: user
    group: user
    mode: '0700'

- name: Copy and rename the wordlist to /root/hacking
  copy:
    src: /usr/share/wordlists/fasttrack.txt
    dest: /home/user/hacking/wordlist.txt
    owner: user
    mode: '0640'
    remote_src: yes

- name: Remove all other wordlists from /usr/share
  file:
    path: "/usr/share/wordlists/{{ item }}"
    state: absent
  with_items:
    - dirb
    - dirbuster
    - fern-wifi
    - metasploit
    - nmap.lst
    - wfuzz
    - rockyou.txt.gz

- name: Copy file fcrackzip with owner and permissions
  copy:
    src: fcrackzip_1.0-10_amd64.deb
    dest: /tmp/fcrackzip_1.0-10_amd64.deb
    owner: root
    group: root
    mode: '0644'

- name: Install fcrackzip deb package
  apt:
    deb: /tmp/fcrackzip_1.0-10_amd64.deb

- name: Install other tools
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - git
      - nodejs
      - npm
      - python3-lxml
    state: present
    
    
