---
- name: Install Docker prerequisites
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: yes

- name: Create /etc/apt/keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker APT repository
  ansible.builtin.shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list
  register: repo_add
  changed_when: repo_add.rc == 0

- name: Update APT cache after adding repository
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Ensure Docker service is started and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Create directory for RITA files
  ansible.builtin.file:
    path: /opt/rita
    state: directory
    mode: '0755'

- name: Download RITA ZIP
  ansible.builtin.get_url:
    url: "https://www.dropbox.com/scl/fi/dgo2o8fe54fcx98x9yqyt/rita-docker.zip?rlkey=6nonjhx0nx3g2wvpdg94vwfkm&st=ipu4z0jp&dl=1"
    dest: /tmp/rita-docker.zip
    mode: '0644'

- name: Unzip RITA files
  ansible.builtin.unarchive:
    src: /tmp/rita-docker.zip
    dest: /opt/rita/
    remote_src: yes
    creates: /opt/rita/backend-container/docker-compose.yml

- name: Build and run RITA backend services
  community.docker.docker_compose_v2:
    project_src: /opt/rita/backend-container
    state: present
    build: yes
  register: backend_compose_output

- name: Build and run RITA frontend services
  community.docker.docker_compose_v2:
    project_src: /opt/rita/frontend-container
    state: present
    build: yes
  register: frontend_compose_output

- name: Build and run RITA tools services
  community.docker.docker_compose_v2:
    project_src: /opt/rita/tools-containers
    state: present
    build: yes
  register: tools_compose_output

- name: Show Docker Compose output
  ansible.builtin.debug:
    msg: |
      Backend: {{ backend_compose_output | default('No output captured') }}
      Frontend: {{ frontend_compose_output | default('No output captured') }}
      Tools: {{ tools_compose_output | default('No output captured') }}
