---
- name: Set password on User ubuntu
  ansible.builtin.user:
    name: ubuntu
    password: "$y$j9T$r1LaddN0V6MPqFmZl5U7C/$4xbYJL5zi/YFU85SL/gXz5UXs3JAXV5dU5CUvTN/WN9"
    update_password: always

- name: Install Docker prerequisites
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - smbclient
      - cifs-utils
      - unzip
    state: present
    update_cache: yes

- name: Create /etc/apt/keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker APT repository
  ansible.builtin.shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list
  register: repo_add
  changed_when: repo_add.rc == 0

- name: Update APT cache after adding repository
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Ensure Docker service is started and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Create mount point
  ansible.builtin.file:
    path: "/mnt/smb_shared"
    state: directory
    mode: "0775"
    
- name: Mount SMB Share (guest)
  ansible.builtin.mount:
    src: "//10.250.232.198/shared"
    path: "/mnt/smb_shared"
    fstype: cifs
    opts: "guest,vers=3.0"
    state: mounted

- name: Copy RITA zip from SMB to destination
  ansible.builtin.copy:
    src: "/mnt/smb_shared/rita-docker.zip"
    dest: "/opt/rita-docker.zip"
    remote_src: true
    mode: "0644"

- name: Copy DFIR-IRIS zip from SMB to destination
  copy:
    src: "/mnt/smb_shared/dfir-iris-custom.zip"
    dest: "/opt/dfir-iris-custom.zip"
    remote_src: true
    mode: "0644"

- name: Create NG-SOAR directory for the yml
  file:
    path: "/opt/NG-SOAR"
    state: directory
    mode: "0755"

- name: Copy NG-SOAR yml from SMB to destination
  copy:
    src: "/mnt/smb_shared/NG-SOAR.yml"
    dest: "/opt/NG-SOAR/NG-SOAR.yml"
    remote_src: true
    mode: "0644"

- name: Unarchive RITA Docker bundle
  ansible.builtin.unarchive:
    src: "/opt/rita-docker.zip"
    dest: "/opt/"
    remote_src: true
    extra_opts: ["-o"]

- name: Unzip rita frontend dist.zip
  ansible.builtin.unarchive:
    src: "/opt/rita-docker/frontend-container/rita-frontend/dist.zip"
    dest: "/opt/rita-docker/frontend-container/rita-frontend"
    remote_src: true
    extra_opts: ["-o"]

- name: Unzip DFIR-IRIS Docker
  unarchive:
    src: "/opt/dfir-iris-custom.zip"
    dest: "/opt/"
    remote_src: true
    extra_opts: ["-o"]

- name: Ensure RITA Docker network exists
  community.docker.docker_network:
    name: rita-network
    state: present

#- name: Ensure NG-SOAR network exists
#  community.docker.docker_network:
#    name: db-net
#    state: present

- name: Login to Docker Hub
  community.docker.docker_login:
    username: demongsoc
    password: "dckr_pat_OzOR3rfLKW3QcFAFUfAi_Je_5_Q"

- name: Build and run RITA backend services
  community.docker.docker_compose_v2:
    project_src: "/opt/rita-docker/backend-container"
    state: present
    build: always
  register: backend_compose_output

- name: Build and run RITA frontend services
  community.docker.docker_compose_v2:
    project_src: "/opt/rita-docker/frontend-container"
    state: present
    build: always
  register: frontend_compose_output
    
- name: Build and run RITA tools services
  community.docker.docker_compose_v2:
    project_src: "/opt/rita-docker/tools-containers"
    state: present
    build: always
  register: tools_compose_output

- name: Build and run DFIR-IRIS
  community.docker.docker_compose_v2:
    project_src: "/opt/dfir-iris-custom"
    state: present
    build: always
  register: dfir_iris_output

- name: Build and run NG-SOAR
  community.docker.docker_compose_v2:
    project_src: "/opt/NG-SOAR"
    state: present
    build: always
  register: NG_SOAR_output

- name: Show Docker Compose output
  ansible.builtin.debug:
    msg: |
      Backend: {{ backend_compose_output | default('No output captured') }}
      Frontend: {{ frontend_compose_output | default('No output captured') }}
      Tools: {{ tools_compose_output | default('No output captured') }}
      DFIR_IRIS: {{ dfir_iris_output | default('No output captured') }}
      NG-SOAR: {{ NG_SOAR_output | default('No output captured') }}

- name: Unmount SMB share
  ansible.builtin.mount:
    path: "/mnt/smb_shared"
    state: unmounted
  when: true
