---
- name: Set password on User ubuntu
  ansible.builtin.user:
    name: ubuntu
    password: "$y$j9T$r1LaddN0V6MPqFmZl5U7C/$4xbYJL5zi/YFU85SL/gXz5UXs3JAXV5dU5CUvTN/WN9"
    update_password: always

- name: Set sequential hostname
  hostname:
    name: "victim{{ '%03d' | format(1000 | random) }}"

